export const API = {
  ROOT: "https://api.themoviedb.org/3/",
  KEY: "720474c3e42189e4e9381b59360765d5",
  PATH: "https://image.tmdb.org/t/p/w500/"
};
export const DISCOVER = {
  ERROR: "ERROR",
  DISCOVER: "DISCOVER",
  DRAWER: "DRAWER"
};

export const INDEX = {
  ERROR: "ERROR",
  NOWPLAYING: "NOWPLAYING",
  LAUNCH: "LAUNCH",
  SEARCH_RESULTS: "SEARCH_RESULTS",
  IMAGE_FOUND: "IMAGE_FOUND",
  INFO_FOUND: "INFO_FOUND",
  CAST_FOUND: "CAST_FOUND",
  REVIEW_FOUND: "REVIEW_FOUND",
  TOP_RATED: "TOP_RATED",
  ANTICIPATED: "ANTICIPATED",
  UPCOMING: "UPCOMING",
  LISTVIEWUPDATE: "LISTVIEWUPDATE",
  FILTER_MOVIES: "FILTER_MOVIES",
  FILTER_TV: "FILTER_TV",
  FILTER_PERSON: "FILTER_PERSON",
  GENRES: "GENRES",
  DISCOVER: "DISCOVER",
  FILTER: "FILTER"
};

export const POPULAR = {
  ERROR: "ERROR",
  PERSON_FOUND: "PERSON_FOUND",
  PERSON_IMAGE_FOUND: "PERSON_IMAGE_FOUND",
  PERSON_DETAIL_FOUND: "PERSON_DETAIL_FOUND",
  MOVIE_FOUND: "MOVIE_FOUND",
  TV_FOUND: "TV_FOUND"
};
export const TVCONST = {
  ERROR: "ERROR",
  ONTHEAIR: "ONTHEAIR",
  AIRINGTODAY: "AIRINGTODAY",
  POPULAR: "POPULAR",
  TOP_RATED: "TOP_RATED",
  IMAGE_FOUND: "IMAGE_FOUND",
  INFO_FOUND: "INFO_FOUND",
  CAST_FOUND: "CAST_FOUND",
  REVIEW_FOUND: "REVIEW_FOUND"
};
